version: '3.0'

services:
  odoo:
    image: odoo:17

    container_name: Odoo_AI_App
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:       
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - POSTGRES_DB=postgres
    restart: always
    networks:
        - odoo-network
    command: ["-u","Odoo_AI_App"]


  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5432"
    networks:
        - odoo-network
networks:
  odoo-network: